// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Map = require("bs-platform/lib/js/map.js");
var $$Set = require("bs-platform/lib/js/set.js");
var Int64 = require("bs-platform/lib/js/int64.js");

function compare(param, param$1) {
  return Int64.compare(param[/* identifier */0], param$1[/* identifier */0]);
}

var $$Set$1 = $$Set.Make(/* module */[/* compare */compare]);

var Node = /* module */[
  /* compare */compare,
  /* Set */$$Set$1
];

var GossipOverview = /* module */[];

var VectorMap = $$Map.Make([compare]);

var VectorClock = /* module */[/* VectorMap */VectorMap];

var Gossip = /* module */[];

exports.Node           = Node;
exports.GossipOverview = GossipOverview;
exports.VectorClock    = VectorClock;
exports.Gossip         = Gossip;
/* Set Not a pure module */
